
[TestEffect]
total_particles = 2
emissionRate = 0.05
life = 4
ASCII = 'J'

    [TestEffect.Movement]
    speed = 40
    angle = 90
    xEmitterPos = 25
    yEmitterPos = 25
    zEmitterPos = 0

    [TestEffect.Deviate]
        [TestEffect.Deviate.Movement]
        speed = 0
        angle = 0

        [TestEffect.Deviate.Life]
        life = 0

        [TestEffect.Deviate.Color]
        startRGBA = [0, 0, 0, 0]
        endRGBA = [0, 0, 0, 0]

        [TestEffect.Deviate.Position]
        x = 0
        y = 0
        z = 0

    [TestEffect.Color]
    startRGBA = [255, 138, 138, 255]
    endRGBA = [255, 138, 1, 55]

