
[TestEffect]
total_particles = 5000
emissionRate = 8200
life = 0.04
ASCII = '[U+00B7]'

    [TestEffect.Movement]
    speed = 5000
    angle = 90
    xEmitterPos = 25
    yEmitterPos = 25
    zEmitterPos = 0
    radialAccel = -10000000
    tangentialAccel = 1000000
        [TestEffect.Movement.Gravity]
        x = 0
        y = 0

    [TestEffect.Deviate]
        [TestEffect.Deviate.Movement]
        speed = 0
        angle = 180
        radialAccel = 0
        tangentialAccel = 0

        [TestEffect.Deviate.Life]
        life = 0

        [TestEffect.Deviate.Color]
        startRGBA = [0, 0, 0, 0]
        endRGBA = [0, 0, 0, 0]

        [TestEffect.Deviate.Position]
        x = 1
        y = 0
        z = 0

    [TestEffect.Color]
    startRGBA = [255, 138, 138, 255]
    endRGBA = [255, 138, 1, 55]

